---
# tasks file for Appstack-Role
- name: Update Repos
  yum:
    name: "*"
    state: latest
- name: Installing openjdk8
  yum:
    name: "{{req_java}}"
    state: present
#  - name: Creating symlink to java
#    alternatives:
#      name: java
#      link: /usr/bin/java
#      path: /usr/lib/jvm/{{set_java}}/bin/java
- name: Create Dir install
  file:
    path: "/opt/install"
    state: directory

- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    shell: /bin/bash
    groups: tomcat,root
    state: present

- name: Download Tomcat9
  get_url:
    url: "{{tomcat_url}}"
    dest: "/opt/install/"

- name: Extract tar.gz
  unarchive:
    src: "/opt/install/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
    dest: "/opt/install/"
    remote_src: yes

- name: Create Symlink for tomcat
  file:
    src: "/opt/install/apache-tomcat-{{req_tomcat_ver}}"
    dest: "/opt/tomcat"
    state: link

- name: modify server.xml file of tomcat
  template:
    src: server.xml.j2
    dest: "/opt/tomcat/conf/server.xml"
    backup: yes

- name: modify context.xml file of tomcat
  template:
    src: context.xml.j2
    dest: "/opt/tomcat/conf/context.xml"
    backup: yes

- name: Download and Deploy MySql JDBC driver
  get_url:
    url: "{{MySql8_jdbc_connector_url}}"
    dest: "/opt/tomcat/lib/"

- name: Download and Deploy keycloak adapters
  get_url:
    url: "{{keycloak_adapter_url}}"
    dest: "/opt/install/"

- name: Extract Keycloak adapter and deploy in the lib
  unarchive:
    src: "/opt/install/keycloak-tomcat-adapter-dist-11.0.3.tar.gz"
    dest: "/opt/tomcat/lib/"
    remote_src: yes

- name: Deploy Student app
  copy:
    src: "student.war"
    dest: "/opt/tomcat/webapps/"
    #remote_src: yes

- name: Deploy Cars Sample app
  copy:
    src: "Cars_Sample_App.war"
    dest: "/opt/tomcat/webapps/"
    #remote_src: yes

- name: Change tomcat home dir ownership & group
  file:
    path: "/opt/tomcat/"
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Deleting files not required from tomcat home dir
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /opt/tomcat/RUNNING.txt
    - /opt/tomcat/RELEASE-NOTES
    - /opt/tomcat/README.md
    - /opt/tomcat/LICENSE
    - /opt/tomcat/CONTRIBUTING.md
    - /opt/tomcat/BUILDING.txt
    - /opt/tomcat/NOTICE

- name: Create system unit file
  template:
    src: "tomcat.service.j2"
    dest: "{{systemd_path}}/tomcat.service"

- name: system deamon reload and enable
  command: "{{item}}"
  with_items:
    - systemctl daemon-reload
    - systemctl enable tomcat.service

- name: Restart of tomcat instances
  service:
    name: tomcat
    state: restarted
    
- name: sleep for 30s
  command: sleep 30

- name: "Keycloak configuration on Student App web"
  template:
    src: "{{ item.src }}"
    dest: "{{ student_web_path }}/{{ item.dest }}"
  loop:
    - { src: 'keycloak-web.xml.j2', dest: 'web.xml' }
    - { src: 'keycloak.json.j2', dest: 'keycloak.json' }

- name: "Keycloak configuration on Student App met"
  template:
    src: "keycloak-context.xml.j2"
    dest: "{{ student_met_path }}/context.xml"
  notify: Restart service tomcat